server:
   port: 8002
   
spring:
  application:
      name: product
  data:
    mongodb:
      authentication-database: new
      username: product
      port: 27017
      host: localhost
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true

  