#server:
#   port: 8080
#
#spring:
#   application:
#      name: gateway
#   cloud:
#    gateway:
#      routes:
#      userProfile:
#          - id: userprofile
#            uri: http://localhost:8001/
#            predicates:
#            - Path=/profile/**
#      product:
#          - id: product
#            uri: http://localhost:8002/
#            predicates:
#            - Path=/products/**
#       cart:
#          - id: cart
#            uri: http://localhost:8003/
#            predicates:
#            - Path=/cart/**
#       order:
#          - id: order
#            uri: http://localhost:8004/
#            predicates:
#            - Path=/order/**

      