server:
   port: 8003
   
spring:
  application:
      name: cart-microservice
  data:
      mongodb:
        database=new
        host=localhost
        port=27017
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true

  